### ISSUE TITLE
Can't export copied images

### ISSUE THREAD

**Issue by bharath-naik** [ether/ep_copy_paste_images#27]
Hi .  The copy paste functionality is great for etherpad .. but whenever I try to export in either html or txt it simply shows " * " replacing the image. 

Ideally it should export whatever the content that was present on etherpad document

**Comment by JohnMcLear** [comment]
TBF It says in the README that export isn't fully supported yet.  Can you look to bring in Export support?  You can reference other plugins for how to do it?

**Comment by woeterman94** [comment]
https://github.com/ether/ep_copy_paste_images/pull/28
